### ISSUE TITLE
Is there any plan to developing a C++ version?

### ISSUE THREAD

**Issue by lwmonster** [gengo/grpc-gateway#15]
Is there any plan to develop a C++ version?   :)

**Comment by yugui** [comment]
No, I don't have any plan to do.

I wonder why you need C++ version.  Since it generates a reverse-proxy, it does not restrict the language  in which you implement your gRPC server.
Also I don't think C++ version will significantly improve the performance of the proxy.

They only benefit which comes to my mind is that C++ version would be able to support arbitrary message without rebuilding the proxy because C++ has a support of DynamicMessage.

What do you think?

**Comment by yugui** [comment]
The question seems to be resolved.

https://groups.google.com/d/msg/grpc-io/JnjCYGPMUms/2TSnRPm7E7cJ

**Comment by yugui** [comment]
> Is there any C/C++ api gateway developed as on today

AFAIK, no.

> are there any examples I can refer to understand how I can link this reverse-proxy with my gRPC server written in C++

It is probably possible to link the generated go code with C++ server since CGO can generate a shared library. 
But can I confirm what you really need in case?  For what purpose are you trying to link the reverse-proxy to your gRPC server? For reducing network latency? For simplicity of deployment and monitoring?
If it is for network latency, I don't think linking solves the problem because the reverse proxy still communicates with the gRPC server over TCP or a  unix domain socket.

**Comment by yanivx** [comment]
![client server](https://user-images.githubusercontent.com/5302788/39113263-77c882ae-46db-11e8-9389-4d5a34494de3.PNG)

This is what I am looking for.

**Comment by yugui** [comment]
![untitled drawing](https://user-images.githubusercontent.com/8161/39233565-a7cfa5b4-48ab-11e8-8a4e-e47da36f33f3.png)

This is how grpc-gateway usually works. So you don't need dive into the complicated world of error handlings, concurrency and garbage collection in CGO. 

With CGO, in theory it is still possible to run the reverse-proxy server in the same process as the gRPC server. But usually it is not very beneficial.
https://github.com/yugui/grpc-gateway/tree/example/embed/examples/cmd/example-cxx-server.

**Comment by yanivx** [comment]
Thank you so much @yugui  :smiley:
