### ISSUE TITLE
array of maps in json

### ISSUE THREAD

**Issue by miekg** [gengo/grpc-gateway#43]
Hi,

Not sure if this a grpc-gateway thing or a proto3 thing. But I cannot get grpc-gateway to parse `[{"2":"3"}]`. The proto3 def that I'm using is this:
````
message mapper {
    map<string,string> m = 1;
}

message Alerts {
  repeated mapper alert = 1;
}
```
[proto3 language def](https://developers.google.com/protocol-buffers/docs/proto3?hl=en#maps) says maps can't be repeated, but `protoc` happily generates (Go) code for this, so....?

Dropping the `[]` and using `{"2":"3"}` works as expected. Is this a bug or the proto3 limitation?

**Comment by yugui** [comment]
I guess both proto3 and grpc-gateway are working fine, but let me confirm.

IIUC, you defined a service which takes an `Alerts` message as a request, and tried to pass exactly `[{"2":"3"}]` as an HTTP request body.
Your generated gateway rejected this request because it expects a JSON object as a request body but received an array of JSON objects.

In this case, an example of the request format which your gateway expects is something like
```json
{
	"alert": [
		{
			"m": {
				"1": "2",
				"3": "4"
			}
		},
		{
			"m": {
				"5": "6"
			}
		}
	]
}
```

FYI,
* the gateway accepted `{"1": "2"}` because JSON unmarshaller just ignores unknown keys.
* proto3 does not allow repeated map fields but allows repeated message fields which contain maps.

**Comment by miekg** [comment]
Thanks for your reply. And, yes exactly what you describe. I will work around it.
